### PR TITLE
fix helm breakage

### PR DESCRIPTION
**Pull request by steckerhalter**
This PR changes only what is really necessary compared to https://github.com/ShingoFukuyama/helm-swoop/pull/124

Feel free to merge whatever you think fits better.

### CODE REVIEW

**Comment by drewbarbs** [comment]
This little patch fixed things for me!

**Comment by mike-hewitson** [comment]
Fixed it for me as well, thank you

**Comment by steckerhalter** [comment]
@mike-hewitson you're welcome...

**Comment by gopar** [comment]
Works \o/

**Comment by codeasone** [comment]
Nicely done. Works a treat.

**Comment by samangh** [comment]
Works for me, thank you @steckerhalter. Fixes issue #58.

@ShingoFukuyama  please merge this  when convenient :-). Thanks!

**Comment by xuchengpeng** [comment]
@steckerhalter  great work

**Comment by takaxp** [comment]
We, Japanese Emacs Community, directly contact with the author so it will be resolved soon 👍

**Comment by ShingoFukuyama** [comment]
Thank you @steckerhalter and everyone here for fixing & checking the issue!
I'm sorry for the very late notice.

**Comment by steckerhalter** [comment]
@ShingoFukuyama No worries, take care

**Pull request merged**
